"""add scheduling tables

Revision ID: 50a2c5ad9cc2
Revises: 9f895badc3d7
Create Date: 2026-09-20 18:13:55.560852

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50a2c5ad9cc2'
down_revision: str | Sequence[str] | None = '9f895badc3d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint(
        'ends_at IS NULL OR ends_at > starts_at',
        name='ck_services_valid_schedule'
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_age_years', sa.Integer(), nullable=False),
    sa.Column('max_age_years', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint('max_age_years >= 0', name='ck_sessions_max_age_nonnegative'),
    sa.CheckConstraint(
        'min_age_years <= max_age_years',
        name='ck_sessions_valid_age_range'
    ),
    sa.CheckConstraint('min_age_years >= 0', name='ck_sessions_min_age_nonnegative'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'room_id', name='uq_sessions_service_room')
    )
    op.create_table('volunteer_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'session_id', 'volunteer_id',
        name='uq_volunteer_assignments_session_volunteer'
    ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_assignments')
    op.drop_table('sessions')
    op.drop_table('volunteers')
    op.drop_table('services')
    op.drop_table('rooms')
    # ### end Alembic commands ###
