"""add pager tables

Revision ID: 6ecddf4bd644
Revises: 50a2c5ad9cc2
Create Date: 2026-09-27 23:26:34.459849

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ecddf4bd644"
down_revision: str | Sequence[str] | None = "50a2c5ad9cc2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pagers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_pagers_code"),
    )
    op.create_table(
        "attendances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(), nullable=False),
        sa.Column("checked_out_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "checked_out_at IS NULL OR checked_out_at >= checked_in_at",
            name="ck_attendances_valid_checkout",
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pager_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pager_id", sa.Uuid(), nullable=False),
        sa.Column("attendance_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "released_at IS NULL OR released_at >= assigned_at",
            name="ck_pager_assignments_valid_release",
        ),
        sa.ForeignKeyConstraint(
            ["attendance_id"],
            ["attendances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pager_id"],
            ["pagers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pager_assignments")
    op.drop_table("attendances")
    op.drop_table("pagers")
    # ### end Alembic commands ###
